---
- name: "5.1. Instalar PostgreSQL, RabbitMQ e Suporte ACL"
  apt:
    name: 
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - rabbitmq-server
      - acl
    state: present
    update_cache: yes

- name: "5.2. Configurar PostgreSQL para ouvir na rede (listen_addresses)"
  lineinfile:
    path: "/etc/postgresql/16/main/postgresql.conf"
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'"
  notify: reiniciar postgres

- name: "5.3. Configurar permissões de rede (pg_hba.conf)"
  blockinfile:
    path: "/etc/postgresql/16/main/pg_hba.conf"
    block: |
      # Permite conexões de todos os nós do cluster via MD5
      host    all             all             127.0.0.1/32            md5
      host    all             all             {{ keepalived_vip }}/32 md5
      host    all             all             10.25.41.0/24           md5
      host    all             all             192.168.132.0/24        md5
  notify: reiniciar postgres

- name: "5.4. Garantir que os serviços estejam ativos e habilitados"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: [postgresql, rabbitmq-server]

- name: "5.5. Definir senha administrativa do PostgreSQL (User: postgres)"
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "{{ database_admin_password }}"
    state: present

- name: "5.6. Criar usuário OpenStack no RabbitMQ"
  rabbitmq_user:
    user: openstack
    password: "{{ rabbitmq_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: "5.7. Validar portas de escuta (Check Final)"
  shell: "ss -tulpn | grep -E '5432|5672'"
  register: port_check
  changed_when: false

- name: "Exibir Status das Portas"
  debug:
    msg: "{{ port_check.stdout_lines }}"
